device-management-toolkit/mps-router

Jenkinsfile

Checkmarx scan worked.  Re-enabling

build(scans): enabled Checkmarx

---

cmd/main.go
internal/db/mpsdb.go

feat(healthcheck): adds flag for checking db status

---

cmd/main.go

closes: Container name of MPS is hardcoded #27

feat(env): add option to override default mps host

---

.github/workflows/release.yml
.releaserc.json

ci(release): adds semantic release to repo

---

.github/workflows/go.yml

ci: add junit test output

---

Dockerfile

build(docker): remove GOARCH build flag

---

CHANGELOG.md

fix: release updated dependencies

---

CHANGELOG.md

docs: updates version in changelog

---

.github/workflows/projectsSync.yaml

ci: add project sync to mps-router

---

.github/workflows/changelog.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docker-image-ci.yml
.github/workflows/docker-image.yml
.github/workflows/go.yml
.github/workflows/release.yml
.github/workflows/semantic.yml

ci: update actions/checkout, update semantic PR

---

.github/workflows/changelog.yml
README.md

docs: align format to match other repositories

---

.github/workflows/go.yml
.gitignore
cmd/main.go
internal/db/mpsdb_test.go
internal/proxy/proxy_test.go

ci: adds codecov, go fmt, go vet, and go lint

---

.github/workflows/release.yml

ci: updates semantic release version

---

.github/workflows/changelog.yml

ci: update changelog generator

---

.github/workflows/trivy-scan.yml

ci: add trivy container scan

---

internal/proxy/proxy.go

fix: removes RFC4122 compliance check on uuid to allow any

---

cmd/main.go
internal/db/manager.go
internal/db/postgres.go
internal/db/postgres_test.go
internal/proxy/proxy.go
internal/proxy/proxy_test.go
internal/test/mockdb.go

refactor: add db interface

---

.github/workflows/release.yml
.releaserc.json

ci: add release tag to docker image

---

.releaserc.json

ci: fix image name for internal docker release

---

.github/workflows/release.yml
.releaserc.json

fix: releaserc format issue

---

.github/workflows/changelog.yml

ci: fix wrong changelog upload

---

CHANGELOG.md

chore: update build tasks and changelog

---

.github/workflows/trivy-scan.yml

ci: add trivy results to github security tab

---

CHANGELOG.md

chore: update build tasks

---

.github/workflows/codeql-analysis.yml

ci: adds security report

---

.github/workflows/trivy-scan.yml

ci: set permissions for trivy-scan at job level

---

CHANGELOG.md

chore: updated dependencies

---

.github/workflows/semantic.yml

ci: update permissions for semantic.yml

---

.github/PULL_REQUEST_TEMPLATE.md

refactor: rename open-amt-cloud-toolkit to device-management-toolkit

---

.github/workflows/trivy-scan.yml

ci: upload trivy result scan

---

.github/workflows/docker-image.yml
.github/workflows/release.yml
.releaserc.json

feat: enable multiarch build

---

Dockerfile

build(docker): adds licensefiles

---

.github/workflows/go.yml
Dockerfile
go.mod

ci: update go to v1.25.x and alpine
